version: '3'
vars:
  DRUSH: ./vendor/bin/drush
env:
  DB_HOST: 'localhost'
  DB_USERNAME: 'alex'
  DB_PASSWORD: 'Test_user_1_p'




tasks:
  drush:
    cmds:
      - '{{.DRUSH}} {{.CLI_ARGS}}'
  uli:
    cmds:
      - '{{.DRUSH}} uli '

  site-install:
    cmds:
      - '{{.DRUSH}} si --existing-config --yes --account-name=admin --account-pass=1234'
      - '{{.DRUSH}} --yes cim'

