version: '3'
vars:
  DRUSH: ./vendor/bin/drush

env:
  DB_HOST: 'localhost'
  DB_USERNAME: 'db'
  DB_PASSWORD: 'db'
#  DB_DATABASE: 'db'


tasks:
  drush:
    cmds:
      - '{{.DRUSH}} {{.CLI_ARGS}}'
  uli:
    cmds:
      - '{{.DRUSH}} uli '

  site-install:
    cmds:
      - '{{.DRUSH}} si --existing-config --yes --account-name=admin --account-pass=1234'
      - '{{.DRUSH}} --yes cim'

